/**
 * Banco de Dados de Armas, Itens e Personagens
 * Contém atributos balanceados, custos, estilos, habilidades exclusivas e regras de status.
 */

const CHARACTERS_DATA = {
    stickman: {
        id: 'stickman',
        name: 'Stickman',
        title: 'O Iniciante Determinado',
        skillName: 'Corte Cruzado (X-Slash)',
        skillDesc: 'Salta e dispara duas lâminas de ar pressurizado em formato de X com alta penetração.',
        desc: 'Equilibrado em todos os aspectos. Perfeito para dominar o ritmo das batalhas e encadear sequências.',
        baseHp: 100,
        baseDamage: 16,
        baseSpeed: 6.2,
        baseDefense: 6,
        baseEnergy: 100,
        critChance: 0.06,
        price: 0,
        color: '#ffffff',
        accentColor: '#00f0ff',
        unlocked: true,
        style: 'standard'
    },
    guerreiro: {
        id: 'guerreiro',
        name: 'Guerreiro',
        title: 'Muralha de Ferro',
        skillName: 'Fúria Sísmica (Earth Slam)',
        skillDesc: 'Ergue a arma com fúria e esmaga o solo, gerando estilhaços de pedra e ondas de choque terrestres.',
        desc: 'Grande vigor e blindagem pesada. Absorve golpes severos e revida com pancadas atordoantes.',
        baseHp: 155,
        baseDamage: 24,
        baseSpeed: 5.2,
        baseDefense: 18,
        baseEnergy: 95,
        critChance: 0.08,
        price: 2500,
        color: '#ff3344',
        accentColor: '#ff8800',
        unlocked: false,
        style: 'warrior'
    },
    ninja: {
        id: 'ninja',
        name: 'Ninja',
        title: 'Vento Silencioso',
        skillName: 'Dança Shinobi (Shurikens & Clone)',
        skillDesc: 'Desaparece num redemoinho de fumaça, arremessa 3 shurikens em leque e reaparece desferindo corte relâmpago.',
        desc: 'Velocidade frenética e recuperação de fôlego veloz. Mestre em esquivas ágeis e reposicionamentos rápidos.',
        baseHp: 95,
        baseDamage: 19,
        baseSpeed: 8.6,
        baseDefense: 5,
        baseEnergy: 135,
        critChance: 0.16,
        price: 5000,
        color: '#00e5ff',
        accentColor: '#1d3557',
        unlocked: false,
        style: 'ninja'
    },
    samurai: {
        id: 'samurai',
        name: 'Samurai',
        title: 'Lâmina Honrada',
        skillName: 'Iaijutsu: Corte Dimensional',
        skillDesc: 'Embainha a espada concentrando foco e corta o espaço em flash instantâneo, rasgando o oponente com múltiplos golpes.',
        desc: 'Domínio milimétrico da lâmina. Harmonia sublime entre precisão cirúrgica, velocidade e impacto.',
        baseHp: 125,
        baseDamage: 29,
        baseSpeed: 7.0,
        baseDefense: 10,
        baseEnergy: 115,
        critChance: 0.14,
        price: 9500,
        color: '#ffb703',
        accentColor: '#d62828',
        unlocked: false,
        style: 'samurai'
    },
    mago: {
        id: 'mago',
        name: 'Arcano',
        title: 'Cybersorcerer do Vórtex',
        skillName: 'Tempestade de Plasma',
        skillDesc: 'Levita canalizando runas arcanas e dispara saraivada de 3 orbes elétricos teleguiados que explodem em choque.',
        desc: 'Canalizador de energia pura. Possui a maior reserva de energia e ataques que sobrecarregam defesas.',
        baseHp: 105,
        baseDamage: 27,
        baseSpeed: 6.6,
        baseDefense: 7,
        baseEnergy: 160,
        critChance: 0.15,
        price: 14000,
        color: '#7209b7',
        accentColor: '#4cc9f0',
        unlocked: false,
        style: 'mage'
    },
    valquiria: {
        id: 'valquiria',
        name: 'Valkyria',
        title: 'A Sentinela Celeste',
        skillName: 'Mergulho Radiante (Lança da Luz)',
        skillDesc: 'Abre asas holográficas celestes, alça voo e mergulha em diagonal à velocidade da luz, criando coluna solar.',
        desc: 'Guerreira celestial com asas holográficas. Extremamente rápida em manobras aéreas e contra-ataques pontuais.',
        baseHp: 120,
        baseDamage: 31,
        baseSpeed: 8.2,
        baseDefense: 11,
        baseEnergy: 125,
        critChance: 0.18,
        price: 20000,
        color: '#f72585',
        accentColor: '#ffe600',
        unlocked: false,
        style: 'valkyrie'
    },
    colossus: {
        id: 'colossus',
        name: 'Titã Goliath',
        title: 'Demolidor Mecânico',
        skillName: 'Propulsão a Jato & Soco Demolidor',
        skillDesc: 'Aciona foguetes dorsais com propulsão bruta imparável e descarrega um soco sísmico que quebra qualquer guarda.',
        desc: 'Construção cibernética titanica. Possui armadura super-reforçada que resiste a atordoamentos e quebra defesas inimigas.',
        baseHp: 185,
        baseDamage: 38,
        baseSpeed: 4.8,
        baseDefense: 24,
        baseEnergy: 90,
        critChance: 0.09,
        price: 26000,
        color: '#4361ee',
        accentColor: '#ff0055',
        unlocked: false,
        style: 'titan'
    },
    shadow: {
        id: 'shadow',
        name: 'Shadow',
        title: 'Entidade do Vazio',
        skillName: 'Vórtice da Singularidade',
        skillDesc: 'Gera um buraco negro gravitacional pulsante que suga o adversário com dano contínuo antes de detonar.',
        desc: 'Formado a partir da matéria escura cósmica. Seus passos distorcem sombras e seus golpes devoram a vitalidade inimiga.',
        baseHp: 140,
        baseDamage: 36,
        baseSpeed: 7.8,
        baseDefense: 13,
        baseEnergy: 150,
        critChance: 0.20,
        price: 32000,
        color: '#c77dff',
        accentColor: '#3c096c',
        unlocked: false,
        style: 'shadow'
    },
    chronos: {
        id: 'chronos',
        name: 'Chronos',
        title: 'O Soberano do Tempo (PERSONAGEM SECRETO)',
        skillName: 'Distorção Temporal do Infinito',
        skillDesc: 'Congela o fluxo do tempo em cúpula cósmica e executa sequência pentagonal de cortes estelares prismáticos.',
        desc: 'Recompensa máxima por conquistar o Modo História. Entidade transcendente com auréola de relógio cósmico e domínio total do combate.',
        baseHp: 165,
        baseDamage: 44,
        baseSpeed: 8.8,
        baseDefense: 18,
        baseEnergy: 180,
        critChance: 0.26,
        price: 0,
        color: '#ffd700',
        accentColor: '#9d4edd',
        unlocked: false,
        isSecret: true,
        style: 'chronos',
        secretUnlockHint: '🏆 Recompensa Suprema: Desbloqueado ao derrotar o Boss Final na Fase 8 do Modo História!'
    }
};

const WEAPONS_DATA = {
    madeira: {
        id: 'madeira',
        name: 'Espada de Madeira',
        type: 'sword',
        desc: 'Espada de carvalho leve para treinos. Movimentação suave e de fácil controle.',
        damage: 10,
        speed: 10,
        critBonus: 0,
        price: 0,
        color: '#b08968',
        glowColor: '#7f5539',
        bladeLength: 42,
        bladeWidth: 4,
        unlocked: true
    },
    ferro: {
        id: 'ferro',
        name: 'Espada de Ferro',
        type: 'sword',
        desc: 'Forjada em aço temperado com empunhadura firme e bom poder cortante.',
        damage: 22,
        speed: 8,
        critBonus: 0.03,
        price: 800,
        color: '#d6d6d6',
        glowColor: '#a8dadc',
        bladeLength: 48,
        bladeWidth: 5,
        unlocked: false
    },
    katana: {
        id: 'katana',
        name: 'Katana Ronin',
        type: 'sword',
        desc: 'Lâmina recurvada afiada a laser com velocidade aerodinâmica e corte limpo.',
        damage: 38,
        speed: 12,
        critBonus: 0.08,
        price: 3500,
        color: '#f8f9fa',
        glowColor: '#00f0ff',
        bladeLength: 52,
        bladeWidth: 3.5,
        unlocked: false
    },
    adagas_veneno: {
        id: 'adagas_veneno',
        name: 'Adagas Peçonhentas',
        type: 'daggers',
        desc: 'Par de lâminas rápidas embebidas em neurotoxina. Cada golpe aplica veneno corrosivo por 2.5s.',
        damage: 30,
        speed: 16,
        critBonus: 0.15,
        price: 6500,
        color: '#38b000',
        glowColor: '#70e000',
        specialEffect: 'poison',
        bladeLength: 32,
        bladeWidth: 3.2,
        unlocked: false
    },
    lanca_plasma: {
        id: 'lanca_plasma',
        name: 'Lança de Plasma Voltaica',
        type: 'spear',
        desc: 'Ponta de plasma energizada com alcance estendido. Causa faíscas elétricas e atinge o oponente à distância.',
        damage: 55,
        speed: 11,
        critBonus: 0.10,
        price: 11000,
        color: '#00f0ff',
        glowColor: '#4cc9f0',
        specialEffect: 'lightning',
        bladeLength: 68,
        bladeWidth: 4,
        unlocked: false
    },
    martelo_titan: {
        id: 'martelo_titan',
        name: 'Martelo dos Titãs',
        type: 'hammer',
        desc: 'Cabeça maciça de titânio. Ataques pesados quebram a guarda do adversário e geram micro-tremores.',
        damage: 82,
        speed: 6,
        critBonus: 0.06,
        price: 16000,
        color: '#6c757d',
        glowColor: '#ff0055',
        specialEffect: 'crush',
        bladeLength: 46,
        bladeWidth: 9,
        unlocked: false
    },
    flamejante: {
        id: 'flamejante',
        name: 'Espada Flamejante',
        type: 'sword',
        desc: 'Irradia labaredas solares, deixando rastro incandescente e incinerando inimigos.',
        damage: 72,
        speed: 10,
        critBonus: 0.12,
        price: 22000,
        color: '#ff5400',
        glowColor: '#ff0055',
        specialEffect: 'fire',
        bladeLength: 54,
        bladeWidth: 6,
        unlocked: false
    },
    foice_espectral: {
        id: 'foice_espectral',
        name: 'Foice Espectral do Abismo',
        type: 'scythe',
        desc: 'Lâmina curva fantasmagórica que suga a força vital do oponente, recuperando 6% do dano em HP.',
        damage: 86,
        speed: 9,
        critBonus: 0.18,
        price: 34000,
        color: '#06d6a0',
        glowColor: '#118ab2',
        specialEffect: 'lifesteal',
        bladeLength: 56,
        bladeWidth: 5.5,
        unlocked: false
    },
    sombria: {
        id: 'sombria',
        name: 'Espada Sombria',
        type: 'sword',
        desc: 'Forjada nas fendas do vácuo. Densa em energia escura que transpassa barreiras defensivas.',
        damage: 102,
        speed: 9,
        critBonus: 0.20,
        price: 48000,
        color: '#10002b',
        glowColor: '#9d4edd',
        specialEffect: 'shadow',
        bladeLength: 58,
        bladeWidth: 6.5,
        unlocked: false
    },
    espada_cronos: {
        id: 'espada_cronos',
        name: 'Lâmina da Singularidade',
        type: 'sword',
        desc: 'Obra-prima forjada com cristal estelar puro. Emite feixes prismáticos e possui chance astronômica de crítico.',
        damage: 125,
        speed: 13,
        critBonus: 0.28,
        price: 70000,
        color: '#ffd166',
        glowColor: '#9d4edd',
        specialEffect: 'prism',
        bladeLength: 60,
        bladeWidth: 5.8,
        unlocked: false
    }
};

const ITEMS_DATA = {
    luvas_guerreiro: {
        id: 'luvas_guerreiro',
        name: 'Luvas do Guerreiro',
        slot: 'gloves',
        desc: 'Punhos reforçados com fibra de carbono, concedendo +10% de dano total em todos os ataques.',
        bonusDamagePct: 0.10,
        price: 600,
        icon: '🥊',
        unlocked: false
    },
    botas_ninja: {
        id: 'botas_ninja',
        name: 'Botas Ninja',
        slot: 'boots',
        desc: 'Solas aerodinâmicas que aumentam em +15% a velocidade de movimento terrestre.',
        bonusSpeedPct: 0.15,
        price: 900,
        icon: '🥷',
        unlocked: false
    },
    amuleto_sombrio: {
        id: 'amuleto_sombrio',
        name: 'Amuleto Sombrio',
        slot: 'amulet',
        desc: 'Cristal místico que amplifica a precisão em pontos vitais, concedendo +6% de chance de crítico.',
        bonusCrit: 0.06,
        price: 1800,
        icon: '🔮',
        unlocked: false
    },
    broquel_espinhos: {
        id: 'broquel_espinhos',
        name: 'Broquel Espinhoso',
        slot: 'shield',
        desc: 'Concede +12 de Defesa e reflete 25% de todo dano bloqueado de volta ao atacante (Thorns).',
        bonusDef: 12,
        thornsPct: 0.25,
        price: 2400,
        icon: '🛡️',
        unlocked: false
    },
    capacete_imperial: {
        id: 'capacete_imperial',
        name: 'Capacete Imperial',
        slot: 'helmet',
        desc: 'Elmo nobre energizado que expande a mente e fôlego, concedendo +25 de Vida e +25 de Energia.',
        bonusHp: 25,
        bonusEnergy: 25,
        price: 2200,
        icon: '🪖',
        unlocked: false
    },
    armadura_placas: {
        id: 'armadura_placas',
        name: 'Armadura de Placas',
        slot: 'armor',
        desc: 'Blindagem de placas metálicas pesadas: concede +40 de Vida máxima e +14 de Defesa.',
        bonusHp: 40,
        bonusDef: 14,
        price: 3200,
        icon: '🦾',
        unlocked: false
    },
    reator_cinetico: {
        id: 'reator_cinetico',
        name: 'Reator Cinético',
        slot: 'reactor',
        desc: 'Núcleo bioenergético que acelera a regeneração de energia do lutador em +45%.',
        energyRegenBonusPct: 0.45,
        price: 3800,
        icon: '⚡',
        unlocked: false
    },
    manto_fantasma: {
        id: 'manto_fantasma',
        name: 'Manto Espectral',
        slot: 'cape',
        desc: 'Capa feita com fios quânticos: amplia o alcance do dash e estende a invulnerabilidade da esquiva.',
        dodgeBonus: true,
        price: 4200,
        icon: '🧣',
        unlocked: false
    },
    anel_vampirico: {
        id: 'anel_vampirico',
        name: 'Anel Sanguinário',
        slot: 'ring',
        desc: 'Selo vampírico: sequências de combo de 4+ golpes restauram 4% da sua Vida Máxima.',
        lifestealCombo: 0.04,
        price: 4800,
        icon: '💍',
        unlocked: false
    },
    emblema_berserker: {
        id: 'emblema_berserker',
        name: 'Emblema Berserker',
        slot: 'badge',
        desc: 'Quando a sua vida estiver abaixo de 35%, o seu dano de ataque aumenta em brutais +30%.',
        berserkThreshold: 0.35,
        berserkBonusDmg: 0.30,
        price: 5200,
        icon: '🔥',
        unlocked: false
    }
};
